FROM python:3.6
MAINTAINER denzow <denzow@gmail.com>

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

WORKDIR /app

RUN pip install -v pip-tools==1.9.0

ADD ./requirements.txt requirements.txt
RUN pip install -r /app/requirements.txt

RUN apt-get update && apt-get install -y curl python
RUN curl https://sdk.cloud.google.com | bash
ENV CONFIG /root/.config/gcloud
ENV PATH /root/google-cloud-sdk/bin:$PATH
#COPY ./credentials $CONFIG/credentials
#COPY ./application_default_credentials.json $CONFIG/application_default_credentials.json
RUN gcloud config set account senta.aihara@gmail.com
RUN gcloud config set project mythic-brook-228516