version: '3.0'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/docker/service/start-server.sh
    volumes:
      - .:/app
      - ~/.config:/root/.config
    expose:
      - 3000
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_DB_NUMBER=0
      - REDIS_DB_PREFIX=local
      - PYTHONUNBUFFERED=1
    links:
      - redis

  nginx:
    image: nginx:1.11.7
    command: /start-nginx.sh
    volumes:
      - ./docker/service_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/service_nginx/default.conf:/etc/nginx/sites-available/default:ro
      - ./docker/service_nginx/default.conf:/etc/nginx/sites-enabled/default:ro
      - ./docker/service_nginx/start-nginx.sh:/start-nginx.sh:ro
    ports:
      - 8000:8000
    links:
      - service

  redis:
    image: redis:3.2.4
    expose:
      - 6379

